infobox/urls.py
from django.urls import path
from infobox.views import CategoryView, InfoboxView, InfoboxUpdateView, CategoryUpdateView, InfoboxDeleteView,\
    CategoryDeleteView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('categories/', CategoryView.as_view(), name='category'),
    path('categories/<int:pk>/', CategoryView.as_view(), name='new_category'),
    path('categories/<int:pk>/edit', CategoryUpdateView.as_view(), name='edit_category'),
    path("categories/<int:category_id>/infobox/new", InfoboxView.as_view(), name="new"),
    path("categories/<int:category_id>/infobox/<int:pk>/new", InfoboxView.as_view(), name="new"),
    path("categories/<int:category_id>/infobox/<int:pk>/edit", InfoboxUpdateView.as_view(), name="edit"),
    path("infobox/parent/<int:parent_id>/child/<int:pk>/edit", InfoboxUpdateView.as_view(), name="edit"),
    path("infobox/<int:pk>/edit", InfoboxUpdateView.as_view(), name="edit"),
    path("infobox/<int:pk>/new", InfoboxView.as_view(), name="new"),
    path("infobox/<int:pk>/delete", InfoboxDeleteView.as_view(), name="delete"),
    path("categories/delete/<int:parent_id>", CategoryDeleteView.as_view(), name="delete_category"),
    path("categories/delete", CategoryDeleteView.as_view(), name="delete_category")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

traveler/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name="home/home.html"), name="home"),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', TemplateView.as_view(template_name="registration/profile.html"), name="profile"),
    path(r'api/v1/api-auth/', include('rest_framework.urls')),
    path(r'api/v1/', include(('infobox.api_urls', "infobox"), namespace="infobox_api")),
    path(r'', include(('infobox.urls', "infobox",), "infobox")),
    path(r'', include(('supplication.urls', "supplication",), "supplication")),
]


if settings.DEBUG is True:
    #  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

infobox/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name=_("Bezeichnung"))
    description = models.TextField(verbose_name=_("Beschreibung"), null=True, blank=True)
    parent = models.ForeignKey("infobox.Category", on_delete=models.SET_NULL, null=True,
                               verbose_name=_("Oberkategorie"), related_name="child_categories")


language_choices = (("Arabisch", "Arabisch"), ("Deutsch", "Deutsch"), ("Türkisch", "Türkisch"), ("Urdu", "Urdu"),)
type_choices = (("Mustahabb", "Mustahabb"), ("Sunnah", "Sunnah"))


class Infobox(models.Model):
    title = models.CharField(max_length=200, verbose_name=_("Bezeichnung"))
    language = models.CharField(max_length=200, verbose_name=_("Typ"), null=True, blank=False, choices=language_choices)
    description = models.TextField(verbose_name=_("Beschreibung"), null=True, blank=True)
    category = models.ForeignKey("infobox.Category", verbose_name=_("Kategorie"), on_delete=models.SET_NULL, null=True,
                                 related_name="infoboxes")
    parent = models.ForeignKey("infobox.Infobox", on_delete=models.CASCADE, null=True)
    # audio = models.FileField(null=True, blank=True, verbose_name="Audiodatei")
    # type = models.CharField(max_length=200, null=True, blank=True, choices=type_choices)

supplication/models.py
from django.db import models
from django.utils.translation import gettext as _


language_choices = (("Arabisch", "Arabisch"), ("Deutsch", "Deutsch"), ("Türkisch", "Türkisch"), ("Urdu", "Urdu"),)
type_choices = (("Mustahabb", "Mustahabb"), ("Sunnah", "Sunnah"))


class Supplication(models.Model):
    type = models.CharField(max_length=200, null=True, blank=True, choices=type_choices, verbose_name=_("Art"))
    infobox = models.ForeignKey("infobox.Infobox", null=True, blank=True, verbose_name=_("Infobox"),
                                on_delete=models.SET_NULL)
    supplication_data = models.OneToOneField("supplication.SupplicationData", null=True, blank=True,
                                             on_delete=models.SET_NULL, verbose_name=_("Stammdaten"))


class SupplicationVariant(models.Model):
    supplication_data = models.OneToOneField("supplication.SupplicationData", null=True, blank=True,
                                             on_delete=models.SET_NULL, verbose_name=_("Stammdaten"))
    parent = models.ForeignKey("supplication.Supplication", null=True, blank=True, on_delete=models.SET_NULL,
                               verbose_name=_("Parent"))


class SupplicationData(models.Model):
    title = models.CharField(max_length=200, verbose_name=_("Bezeichnung"))
    description = models.TextField(verbose_name=_("Beschreibung"), null=True, blank=True)
    audio = models.FileField(null=True, blank=True, verbose_name=_("Audiodatei"))
    phonetic_spelling = models.TextField(null=True, blank=True, verbose_name=_("Lautschrift"))
    language = models.CharField(max_length=200, verbose_name=_("Sprache"), null=True, blank=False,
                                choices=language_choices)

infobox/forms.py
from django import forms
from infobox.models import Category, Infobox


class CategoryCreationForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ("title", "description", )

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"


class InfoboxCreationForm(forms.ModelForm):
    class Meta:
        model = Infobox
        fields = ("language", "title", "description",)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        for visible in self.visible_fields():
            if type(visible.field) != forms.FileField:
                visible.field.widget.attrs["class"] = "form-control"

    def clean_language(self):
        language = self.cleaned_data['language']
        if self.instance.parent_id:
            language_occurence = 0
            if self.instance.pk:
                language_occurence += self.instance.parent.infobox_set.filter(
                    language=language).exclude(pk=self.instance.pk).count()
            else:
                language_occurence += self.instance.parent.infobox_set.filter(language=language).count()
            if language == self.instance.parent.language:
                language_occurence += 1
            if language_occurence > 0:
                self.add_error("language", "Eine Infobox in dieser Sprache ist bereits angelegt")
        return language

infobox/views.py
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, UpdateView
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from infobox.models import Category, Infobox
from infobox.forms import CategoryCreationForm, InfoboxCreationForm
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.http.response import JsonResponse


class CategoryView(LoginRequiredMixin, CreateView):
    template_name = "infobox/category.html"
    form_class = CategoryCreationForm

    def get_queryset(self):
        category_id = self.kwargs.get("pk")
        if category_id:
            return Category.objects.filter(parent_id=category_id)
        else:
            return Category.objects.filter(parent_id__isnull=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = self.get_queryset()
        category_id = self.kwargs.get("pk")
        if category_id:
            context["object"] = get_object_or_404(Category, pk=category_id)
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        parent_id = self.kwargs.get("pk")
        if parent_id:
            instance.parent_id = parent_id
        return super().form_valid(form)

    def get_success_url(self):
        category_id = self.kwargs.get("pk")
        if category_id:
            return reverse_lazy("infobox:new_category", kwargs={"pk": category_id})
        else:
            return reverse_lazy("infobox:category")


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "infobox/edit_category.html"
    form_class = CategoryCreationForm

    def get_object(self, queryset=None):
        return Category.objects.get(pk=self.kwargs.get("pk"))

    def get_success_url(self):
        category_id = self.kwargs.get("pk")
        return reverse_lazy("infobox:edit_category", kwargs={"pk": category_id})


class InfoboxView(LoginRequiredMixin, CreateView):
    form_class = InfoboxCreationForm
    success_url = reverse_lazy("infobox:category")
    template_name = "infobox/new_infobox.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get("pk")
        parent = None
        if pk:
            parent = get_object_or_404(Infobox, pk=pk)
            context["parent"] = parent
        context["parent_id"] = pk
        category_id = self.kwargs.get("category_id")
        if category_id:
            context["category_id"] = category_id
            context["category"] = get_object_or_404(Category, pk=category_id)
        else:
            category_id = parent.category_id
            context["category_id"] = category_id
            context["category"] = get_object_or_404(Category, pk=category_id)

        if parent:
            context["is_variant"] = True
        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        instance = form.instance
        category_id = self.kwargs.get("category_id")
        infobox_parent_id = self.kwargs.get("pk")

        if infobox_parent_id:
            instance.parent_id = infobox_parent_id
            return form

        if category_id:
            instance.category_id = category_id
        return form

    def get_success_url(self):
        category_id = self.kwargs.get("category_id")
        infobox_parent_id = self.kwargs.get("pk")

        if category_id:
            return reverse_lazy("infobox:edit", kwargs={"pk": self.object.pk, "category_id": category_id})
        else:
            return reverse_lazy("infobox:edit", kwargs={"pk": self.object.pk, "parent_id": infobox_parent_id})


class InfoboxUpdateView(LoginRequiredMixin, UpdateView):
    form_class = InfoboxCreationForm
    template_name = "infobox/edit_infobox.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Infobox, pk=self.kwargs.get("pk"))

    def get_success_url(self):
        if self.object.category_id:
            return reverse_lazy("infobox:edit", kwargs={"pk": self.object.pk, "category_id": self.object.category_id})
        else:
            return reverse_lazy("infobox:edit", kwargs={"pk": self.object.pk, "parent_id": self.object.parent_id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        parent_id = self.kwargs.get("parent_id")
        child_id = self.kwargs.get("pk")
        if parent_id:
            parent = get_object_or_404(Infobox, pk=parent_id)
        else:
            print(f"????????????? {child_id}")
            child = get_object_or_404(Infobox, pk=child_id)
            print(f"ho: {child.parent_id}")
            parent = child.parent
        print(f"hey: {parent}")
        context["parent"] = parent
        context["parent_id"] = parent_id
        category_id = self.kwargs.get("category_id")

        if category_id:
            context["category_id"] = category_id
        else:
            category_id = parent.category_id
            context["category_id"] = category_id

        if category_id:
            category = get_object_or_404(Category, pk=category_id)
            context["category"] = category

        is_variant = None
        if parent:
            is_variant = True
        context["is_variant"] = is_variant

        if is_variant:
            context["object_list"] = parent.infobox_set.exclude(id=child_id)
        else:
            context["object_list"] = self.object.infobox_set.all()
        return context


class InfoboxDeleteView(generic.View):
    def post(self, request, *args, **kwargs):
        infobox = get_object_or_404(Infobox, pk=self.kwargs.get("pk"))
        if infobox.category:
            category = infobox.category
            infobox.delete()
            return HttpResponseRedirect(reverse_lazy("infobox:new_category", kwargs={"pk": category.pk}))
        else:
            parent = infobox.parent
            category = infobox.parent.category
            infobox.delete()
            return HttpResponseRedirect(
                reverse_lazy("infobox:edit", kwargs={"pk": parent.pk, "category_id": category.id}))


class CategoryDeleteView(generic.View):
    def post(self, request, *args, **kwargs):
        print(f"hallo: {self.request.POST.getlist('item')}")
        categories = Category.objects.filter(pk__in=self.request.POST.getlist("item"))
        categories_with_infoboxes = categories.annotate(
            infoboxes_count=Count("infoboxes")).filter(infoboxes_count__gt=0)
        categories_with_infoboxes_count = categories_with_infoboxes.count()

        if categories_with_infoboxes_count > 0:
            return JsonResponse({"error": "Sie können keine Kategorien mit Infoboxen löschen"}, status=400)

        categories_with_sub_categories = categories.annotate(
            child_categories_count=Count("child_categories")).filter(child_categories_count__gt=0)

        categories_with_sub_categories_count = categories_with_sub_categories.count()

        if categories_with_sub_categories_count > 0:
            return JsonResponse({"error": "Sie können keine Kategorien mit Unterkategorien löschen"}, status=400)

        current_category_parent_id = self.kwargs.get("parent_id")

        categories.delete()

        print(f"??????? {current_category_parent_id}")

        if current_category_parent_id:
            return JsonResponse(
                {"redirect_url": reverse_lazy("infobox:new_category", kwargs={"pk": current_category_parent_id})},
                status=200)
        else:
            return JsonResponse({"redirect_url": reverse_lazy("infobox:category")}, status=200)

infobox/templates/infobox/snippets/category_delete_panel.html
<div class="row text-right">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
            <div class="col-md-8"></div>
            <div class="col-md-4">
                <div class="text-right">
                        <div class="input-group">
                            <select class="form-control" id="action_field">
                              <option value="">---------</option>
                              <option value="delete">Löschen</option>
                            </select>
                        <div class="input-group-btn">
                          <button class="btn btn-primary" id="delete_btn" type="submit" disabled>
                              Aktion ausführen
                          </button>
                        </div>
                      </div>
                </div>
                <p id="action_error" style="color:red;"></p>
            </div>
        </div>
      </div>
    </div>
</div>

<script>
    var action_form = document.getElementById("action_form");
    var action_field = document.getElementById("action_field");
    var delete_btn = document.getElementById("delete_btn");
    var action_error_tag = document.getElementById("action_error");

    var change_button_color_when_sub_categories_or_not = function(option_value){
      {% if object.parent_id is None %}
        if(option_value === "delete"){
            //delete_btn.className = delete_btn.className.replace("btn-primary", "btn-danger");
        }else{
            //delete_btn.className = delete_btn.className.replace("btn-danger", "btn-primary");
        }
      {% endif %}
    };

    var change_action_url_of_form = function(action_field){
      if(action_field.value === "delete"){
          action_form.setAttribute("action", "{% url 'infobox:delete_category' %}");
      }else{
          action_form.removeAttribute("action");
      }
    };

    change_button_color_when_sub_categories_or_not(action_field.value);

    change_action_url_of_form(action_field);

    action_field.onchange = function(e){
      if(this.value === ""){
        delete_btn.setAttribute("disabled", "");
      }else {
        delete_btn.removeAttribute("disabled");
      }

      change_action_url_of_form(action_field);

      change_button_color_when_sub_categories_or_not(this.value);

    };

    action_form.onsubmit = function(e){
        e.preventDefault();
        var categories_to_delete_html_elements = document.getElementsByClassName("checkbox_category");
        var categories_to_delete = [];

        var q = "";
        for(var i=0;i<categories_to_delete_html_elements.length; i++){
            var category_el = categories_to_delete_html_elements[i];
            if(category_el.checked){
                categories_to_delete.push(category_el.value);
                q = q + "item=" + category_el.value + "&";
            }
        }
        q += "csrfmiddlewaretoken" +  "={{ csrf_token }}";

        var action_url = " {% if object.parent_id %}{% url 'infobox:delete_category' parent_id=object.parent_id %}{% else %}{% url 'infobox:delete_category' %}{% endif %}";

        $.post(action_url,
            q, function(data, status, xhr){
                var response = JSON.parse(xhr.responseText);
                window.location.replace(response.redirect_url);
            }
        ).fail(function(xhr, status, error) {
            // error handling
            var response = JSON.parse(xhr.responseText);
            action_error_tag.innerHTML = response.error;
        });
    };

</script>

infobox/templates/infobox/snippets/category_list.html
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Kategorien <small>Navigation</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li class="dropdown" style="visibility: hidden;">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">

              </ul>
            </li>
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Titel</th>
                            <th class="col-md-2"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <a style="text-decoration: underline;" href="{% url "infobox:category" %}">...</a>
                            </td>
                            <td></td>
                        </tr>
                        {% if object.parent %}
                            <tr>
                                <td>
                                    <p><a href="{% url 'infobox:new_category' pk=object.parent.pk %}" style="text-decoration: underline;">{{ object.parent.title }}</a></p>
                                </td>
                                <td></td>
                            </tr>
                        {% endif %}
                        {% if object %}
                            <tr class="active">
                                <td>
                                    <p>
                                        <a href="{% url 'infobox:new_category' pk=object.pk %}" style="text-decoration: underline;">{{ object.title }}</a>
                                        <a href="{% url 'infobox:edit_category' pk=object.pk %}"><span class="glyphicon glyphicon-edit"></span></a>

                                    </p>
                                    {% for infobox in  object.infoboxes.all %}
                                        <p>&nbsp;&nbsp;&nbsp;<a>{{ infobox.title }}</a>
                                            <a href="{% url 'infobox:edit' pk=infobox.pk category_id=object.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                                            {{ infobox.language }}
                                            {% for variant in infobox.infobox_set.all %}
                                                {{ variant.language }}
                                            {% endfor %}
                                        </p>

                                    {% endfor %}
                                </td>
                                <td class="text-right">
                                    <div class="form-group">
                                        <div class="btn-group" style="padding:0;">
                                            <a class="btn" href="{% url 'infobox:new' category_id=object.pk %}" type="button" style="display:inline-block; border:none; text-decoration: none;padding: 0;margin: 0;background:transparent;">
                                                <span class="glyphicon glyphicon-plus"></span>
                                            </a>
                                        </div>

                                        <div class="btn-group" style="padding:0;">
                                            <input class="checkbox_category" type="checkbox" value="{{ object.pk }}" name="item" style="display:inline-block; border:none; text-decoration: none;padding: 0;margin: 0;background:transparent;">
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endif %}
                        {% for object in object_list %}
                            <tr>
                                <td>
                                    <p><a href="{% url 'infobox:new_category' pk=object.pk %}" style="text-decoration: underline;">{{ object.title }}</a></p>
                                </td>
                                <td class="text-right">
                                    <div class="btn-group" style="padding:0;">
                                        <input class="checkbox_category" type="checkbox" value="{{ object.pk }}" name="item" style="display:inline-block; border:none; text-decoration: none;padding: 0;margin: 0;background:transparent;">
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
      </div>
    </div>
</div>

infobox/templates/infobox/snippets/infobox_delete_panel.html
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
            <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                <div class="text-right">
                     <form id="action_form" method="POST">{% csrf_token %}
                        <div class="input-group">
                            <select class="form-control" id="action_field">
                              <option value="">---------</option>
                              <option value="delete">Löschen</option>
                            </select>
                        <div class="input-group-btn">
                          <button class="btn btn-primary" id="delete_btn" type="submit" disabled>
                              Aktion ausführen
                          </button>
                        </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </div>
</div>


<script>
    var action_form = document.getElementById("action_form");
    var action_field = document.getElementById("action_field");
    var delete_btn = document.getElementById("delete_btn");


    var change_button_color_when_variant_or_not = function(option_value){
      {% if object.parent_id is None %}
        if(option_value === "delete"){
            delete_btn.className = delete_btn.className.replace("btn-primary", "btn-danger");
        }else{
            delete_btn.className = delete_btn.className.replace("btn-danger", "btn-primary");
        }
      {% endif %}
    };

    var change_action_url_of_form = function(action_field){
      if(action_field.value === "delete"){
          action_form.setAttribute("action", "{% url 'infobox:delete' pk=object.pk %}");
      }else{
          action_form.removeAttribute("action");
      }
    };

    change_button_color_when_variant_or_not(action_field.value);
    change_action_url_of_form(action_field);


    action_field.onchange = function(e){
      if(this.value === ""){
        delete_btn.setAttribute("disabled", "");
      }else {
        delete_btn.removeAttribute("disabled");
      }

      change_action_url_of_form(action_field);

      change_button_color_when_variant_or_not(this.value);

    };
</script>

infobox/templates/infobox/snippets/infobox_languages.html
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Andere Sprachen</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li class="dropdown" style="visibility: hidden;">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">

              </ul>
            </li>
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                <div class="text-center">
                    {% if object.category_id %}
                        <a href="{% url 'infobox:new' pk=object.pk %}" class="btn btn-info"><span class="glyphicon glyphicon-plus"></span> Neue Variante</a>
                    {% endif %}
                    <br/><br/>
                </div>
                {% if object_list or parent %}
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Titel</th>
                                <th>Sprache</th>
                                <th class="col-md-2 text-right"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if parent %}
                                <tr>
                                    <td>{{ parent.title }}</td>
                                    <td>{{ parent.language }}</td>
                                    <td>
                                        <div class="form-group">
                                            <div class="btn-group" style="padding:0;">
                                                <a class="btn" href="{% url 'infobox:edit' pk=parent.pk category_id=parent.category_id %}" type="button" style="display:inline-block; border:none; text-decoration: none;padding: 0;margin: 0;background:transparent;">
                                                    <span class="glyphicon glyphicon-pencil"></span>
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            {% endif %}
                            {% for instance in object_list %}
                                <tr>
                                    <td>
                                        <p>{{ instance.title }}</p>
                                    </td>
                                    <td>{{ instance.language }}</td>
                                    <td>
                                        <div class="form-group">
                                            <div class="btn-group" style="padding:0;">
                                                <a class="btn" href="{% url 'infobox:edit' pk=instance.pk parent_id=object.pk %}" type="button" style="display:inline-block; border:none; text-decoration: none;padding: 0;margin: 0;background:transparent;">
                                                    <span class="glyphicon glyphicon-pencil"></span>
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div class="text-center">
                        <p class="help-block" style="font-size:18px;">Kein Eintrag vorhanden</p>
                    </div>
                {% endif %}
            </div>
        </div>
      </div>
    </div>
</div>