infobox/urls.py
from django.urls import path
from infobox.views import CategoryView, InfoboxView, InfoboxUpdateView, CategoryUpdateView, InfoboxDeleteView,\
    CategoryDeleteView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('categories/', CategoryView.as_view(), name='category'),
    path('categories/<int:pk>/', CategoryView.as_view(), name='new_category'),
    path('categories/<int:pk>/edit', CategoryUpdateView.as_view(), name='edit_category'),
    path("categories/<int:category_id>/infobox/new", InfoboxView.as_view(), name="new"),
    path("categories/<int:category_id>/infobox/<int:pk>/new", InfoboxView.as_view(), name="new"),
    path("categories/<int:category_id>/infobox/<int:pk>/edit", InfoboxUpdateView.as_view(), name="edit"),
    path("infobox/parent/<int:parent_id>/child/<int:pk>/edit", InfoboxUpdateView.as_view(), name="edit"),
    path("infobox/<int:pk>/edit", InfoboxUpdateView.as_view(), name="edit"),
    path("infobox/<int:pk>/new", InfoboxView.as_view(), name="new"),
    path("infobox/<int:pk>/delete", InfoboxDeleteView.as_view(), name="delete"),
    path("categories/delete/<int:parent_id>", CategoryDeleteView.as_view(), name="delete_category"),
    path("categories/delete", CategoryDeleteView.as_view(), name="delete_category")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supplication/urls.py
from django.urls import path
from supplication.views import NewSupplicationView, UpdateSupplicationView, NewSupplicationVariantView, \
    UpdateSupplicationVariantView, SupplicationDeleteView, SupplicationVariantDeleteView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("infobox/<int:pk>/supplication/new", NewSupplicationView.as_view(), name="new"),
    path("infobox/<int:pk>/supplication/<int:supplication_id>/edit", UpdateSupplicationView.as_view(), name="edit"),
    path("infobox/<int:pk>/supplication/<int:supplication_id>/delete", SupplicationDeleteView.as_view(), name="delete"),
    path("infobox/<int:pk>/supplication/<int:supplication_id>/new", NewSupplicationVariantView.as_view(),
         name="new_variant"),
    path("infobox/<int:pk>/supplication/<int:supplication_id>/variant/<int:supplication_variant_id>/edit",
         UpdateSupplicationVariantView.as_view(),
         name="edit_variant"),
    path("infobox/<int:pk>/supplication/<int:supplication_id>/variant/<int:supplication_variant_id>/delete",
         SupplicationVariantDeleteView.as_view(),
         name="delete_variant"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

traveler/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name="home/home.html"), name="home"),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', TemplateView.as_view(template_name="registration/profile.html"), name="profile"),
    path(r'api/v1/api-auth/', include('rest_framework.urls')),
    path(r'api/v1/', include(('infobox.api_urls', "infobox"), namespace="infobox_api")),
    path(r'', include(('infobox.urls', "infobox",), "infobox")),
    path(r'', include(('supplication.urls', "supplication",), "supplication")),
]


if settings.DEBUG is True:
    #  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

supplication/models.py
from django.db import models
from django.utils.translation import gettext as _


language_choices = (("Arabisch", "Arabisch"), ("Deutsch", "Deutsch"), ("Türkisch", "Türkisch"), ("Urdu", "Urdu"),)
type_choices = (("Mustahabb", "Mustahabb"), ("Sunnah", "Sunnah"))


class Supplication(models.Model):
    type = models.CharField(max_length=200, null=True, blank=True, choices=type_choices, verbose_name=_("Art"))
    infobox = models.ForeignKey("infobox.Infobox", null=True, blank=True, verbose_name=_("Infobox"),
                                on_delete=models.SET_NULL)
    supplication_data = models.OneToOneField("supplication.SupplicationData", null=True, blank=True,
                                             on_delete=models.SET_NULL, verbose_name=_("Stammdaten"))


class SupplicationVariant(models.Model):
    supplication_data = models.OneToOneField("supplication.SupplicationData", null=True, blank=True,
                                             on_delete=models.SET_NULL, verbose_name=_("Stammdaten"))
    parent = models.ForeignKey("supplication.Supplication", null=True, blank=True, on_delete=models.SET_NULL,
                               verbose_name=_("Parent"))


class SupplicationData(models.Model):
    title = models.CharField(max_length=200, verbose_name=_("Bezeichnung"))
    description = models.TextField(verbose_name=_("Beschreibung"), null=True, blank=True)
    audio = models.FileField(null=True, blank=True, verbose_name=_("Audiodatei"))
    phonetic_spelling = models.TextField(null=True, blank=True, verbose_name=_("Lautschrift"))
    language = models.CharField(max_length=200, verbose_name=_("Sprache"), null=True, blank=False,
                                choices=language_choices)

supplication/forms.py
from django import forms

from supplication.models import SupplicationData, Supplication, SupplicationVariant


class SupplicationDataForm(forms.ModelForm):
    class Meta:
        model = SupplicationData
        fields = ("title", "description", "audio", "language", "phonetic_spelling",)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        for visible in self.visible_fields():
            if type(visible.field) != forms.FileField:
                visible.field.widget.attrs["class"] = "form-control"


class SupplicationForm(forms.ModelForm):
    class Meta:
        model = Supplication
        fields = ("type",)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        for visible in self.visible_fields():
            if type(visible.field) != forms.FileField:
                visible.field.widget.attrs["class"] = "form-control"


class SupplicationVariantForm(forms.ModelForm):
    class Meta:
        model = SupplicationVariant
        fields = ()

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        for visible in self.visible_fields():
            if type(visible.field) != forms.FileField:
                visible.field.widget.attrs["class"] = "form-control"

supplication/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import View
# Create your views here.
from infobox.models import Infobox
from supplication.forms import SupplicationDataForm, SupplicationForm, SupplicationVariantForm
from django.db import transaction
from supplication.models import Supplication, SupplicationVariant


class NewSupplicationView(View):
    template_name = "supplication/new_supplication.html"
    form = None
    supplication_form = None

    def get(self, request, **kwargs):
        context = self.get_context()
        return render(request, template_name=self.template_name, context=context)

    def get_context(self):
        infobox = get_object_or_404(Infobox, pk=self.kwargs.get("pk"))
        self.form = self.get_data_form()
        self.supplication_form = self.get_supplication_form()
        context = {"infobox": infobox, "category": infobox.category, "form": self.form,
                   "category_id": infobox.category_id, "supplication_form": self.supplication_form}
        return context

    def get_data_form(self):
        if self.request.POST:
            data_form = SupplicationDataForm(data=self.request.POST, files=self.request.FILES, prefix="data")
        else:
            data_form = SupplicationDataForm(prefix="data")
        return data_form

    def get_supplication_form(self):
        if self.request.POST:
            supplication_form = SupplicationForm(data=self.request.POST, prefix="supplication")
        else:
            supplication_form = SupplicationForm(prefix="supplication")
        return supplication_form

    @transaction.atomic
    def post(self, request, **kwargs):
        context = self.get_context()
        infobox = context.get("infobox")
        if self.form.is_valid() is True and self.supplication_form.is_valid() is True:
            supplication_data = self.form.save()
            supplication = self.supplication_form.save()
            supplication.supplication_data = supplication_data
            supplication.infobox = infobox
            supplication.save()
            return HttpResponseRedirect(reverse_lazy("infobox:edit",
                                                     kwargs={"pk": infobox.pk, "category_id": infobox.category_id}))
        else:
            return render(request, template_name=self.template_name, context=context)


class UpdateSupplicationView(View):
    template_name = "supplication/update_supplication.html"
    form = None
    supplication_form = None

    def get(self, request, **kwargs):
        context = self.get_context()
        return render(request, template_name=self.template_name, context=context)

    def get_context(self):
        infobox = get_object_or_404(Infobox, pk=self.kwargs.get("pk"))
        supplication = get_object_or_404(Supplication, pk=self.kwargs.get("supplication_id"))
        supplication_data = supplication.supplication_data
        self.form = self.get_data_form(supplication_data)
        self.supplication_form = self.get_supplication_form(supplication)
        context = {"infobox": infobox, "category": infobox.category, "form": self.form,
                   "category_id": infobox.category_id, "supplication_form": self.supplication_form,
                   "supplication_data": supplication_data, "supplication": supplication
                   }
        return context

    def get_data_form(self, supplication_data):
        if self.request.POST:
            data_form = SupplicationDataForm(data=self.request.POST, files=self.request.FILES,
                                             instance=supplication_data, prefix="data")
        else:
            data_form = SupplicationDataForm(prefix="data", instance=supplication_data)
        return data_form

    def get_supplication_form(self, supplication):
        if self.request.POST:
            supplication_form = SupplicationForm(data=self.request.POST, instance=supplication, prefix="supplication")
        else:
            supplication_form = SupplicationForm(prefix="supplication", instance=supplication)
        return supplication_form

    @transaction.atomic
    def post(self, request, **kwargs):
        context = self.get_context()
        infobox = context.get("infobox")
        if self.form.is_valid() is True and self.supplication_form.is_valid() is True:
            self.form.save()
            supplication = self.supplication_form.save()
            return HttpResponseRedirect(reverse_lazy("supplication:edit",
                                                     kwargs={"pk": infobox.pk, "supplication_id": supplication.pk}))
        else:
            return render(request, template_name=self.template_name, context=context)


class NewSupplicationVariantView(View):
    template_name = "supplication/new_variant.html"
    form = None
    supplication_variant_form = None

    def get(self, request, **kwargs):
        context = self.get_context()
        return render(request, template_name=self.template_name, context=context)

    def get_context(self):
        infobox = get_object_or_404(Infobox, pk=self.kwargs.get("pk"))
        self.form = self.get_data_form()
        parent_supplication = get_object_or_404(Supplication, pk=self.kwargs.get("supplication_id"))
        self.supplication_variant_form = self.get_supplication_variant_form()
        context = {"infobox": infobox, "category": infobox.category, "category_id": infobox.category_id,
                   "form": self.form, "supplication_form": self.supplication_variant_form,
                   "parent_supplication_data": parent_supplication.supplication_data}
        return context

    def get_data_form(self):
        if self.request.POST:
            data_form = SupplicationDataForm(data=self.request.POST, files=self.request.FILES, prefix="data")
        else:
            data_form = SupplicationDataForm(prefix="data")
        return data_form

    def get_supplication_variant_form(self):
        if self.request.POST:
            supplication_form = SupplicationVariantForm(data=self.request.POST, prefix="supplication")
        else:
            supplication_form = SupplicationVariantForm(prefix="supplication")
        return supplication_form

    @transaction.atomic
    def post(self, request, **kwargs):
        context = self.get_context()
        infobox = context.get("infobox")
        if self.form.is_valid() is True and self.supplication_variant_form.is_valid() is True:
            supplication_data = self.form.save()
            supplication_variant = self.supplication_variant_form.save()
            supplication_variant.supplication_data = supplication_data
            supplication_variant.parent_id = self.kwargs.get("supplication_id")
            supplication_variant.save()
            return HttpResponseRedirect(reverse_lazy("supplication:edit",
                                                     kwargs={"pk": infobox.pk,
                                                             "supplication_id": self.kwargs.get("supplication_id")}))
        else:
            return render(request, template_name=self.template_name, context=context)


class UpdateSupplicationVariantView(View):
    template_name = "supplication/update_variant.html"
    form = None
    supplication_variant_form = None

    def get(self, request, **kwargs):
        context = self.get_context()
        return render(request, template_name=self.template_name, context=context)

    def get_context(self):
        infobox = get_object_or_404(Infobox, pk=self.kwargs.get("pk"))
        supplication_variant = get_object_or_404(SupplicationVariant, pk=self.kwargs.get("supplication_variant_id"))
        parent_supplication = supplication_variant.parent
        parent_supplication_data = parent_supplication.supplication_data
        supplication_variant_data = supplication_variant.supplication_data
        self.form = self.get_data_form(supplication_variant_data)
        self.supplication_variant_form = self.get_supplication_variant_form(supplication_variant)
        context = {"infobox": infobox, "category": infobox.category, "form": self.form,
                   "category_id": infobox.category_id, "supplication_form": self.supplication_variant_form,
                   "supplication_data": supplication_variant_data, "supplication": supplication_variant,
                   "parent_supplication": parent_supplication, "parent_supplication_data": parent_supplication_data
                   }
        return context

    def get_data_form(self, supplication_data):
        if self.request.POST:
            data_form = SupplicationDataForm(data=self.request.POST, files=self.request.FILES,
                                             instance=supplication_data, prefix="data")
        else:
            data_form = SupplicationDataForm(prefix="data", instance=supplication_data)
        return data_form

    def get_supplication_variant_form(self, supplication_variant):
        if self.request.POST:
            supplication_form = SupplicationVariantForm(data=self.request.POST, instance=supplication_variant,
                                                        prefix="supplication")
        else:
            supplication_form = SupplicationVariantForm(prefix="supplication", instance=supplication_variant)
        return supplication_form

    @transaction.atomic
    def post(self, request, **kwargs):
        context = self.get_context()
        infobox = context.get("infobox")
        supplication_parent = context.get("parent_supplication")
        if self.form.is_valid() is True and self.supplication_variant_form.is_valid() is True:
            self.form.save()
            supplication_variant = self.supplication_variant_form.save()
            return HttpResponseRedirect(
                reverse_lazy(

supplication/templates/supplication/delete_panel.html
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
            <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                <div class="text-right">
                     <form id="action_form" method="POST">{% csrf_token %}
                        <div class="input-group">
                            <select class="form-control" id="action_field">
                              <option value="">---------</option>
                              <option value="delete">Löschen</option>
                            </select>
                        <div class="input-group-btn">
                          <button class="btn btn-primary" id="delete_btn" type="submit" disabled>
                              Aktion ausführen
                          </button>
                        </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </div>
</div>


<script>
    var action_form = document.getElementById("action_form");
    var action_field = document.getElementById("action_field");
    var delete_btn = document.getElementById("delete_btn");


    var change_button_color_when_variant_or_not = function(option_value){
      {% if object.parent_id is None %}
        if(option_value === "delete"){
            delete_btn.className = delete_btn.className.replace("btn-primary", "btn-danger");
        }else{
            delete_btn.className = delete_btn.className.replace("btn-danger", "btn-primary");
        }
      {% endif %}
    };

    var change_action_url_of_form = function(action_field){
      if(action_field.value === "delete"){
          action_form.setAttribute("action", "{{ delete_url }}");
      }else{
          action_form.removeAttribute("action");
      }
    };

    change_button_color_when_variant_or_not(action_field.value);
    change_action_url_of_form(action_field);


    action_field.onchange = function(e){
      if(this.value === ""){
        delete_btn.setAttribute("disabled", "");
      }else {
        delete_btn.removeAttribute("disabled");
      }

      change_action_url_of_form(action_field);

      change_button_color_when_variant_or_not(this.value);

    };
</script>

supplication/templates/supplication/new_supplication.html
{% extends 'base/base.html' %}


{% block navigation %}
    <li>
        <span><a href="{% url 'infobox:category' %}">Kategorien</a></span>
    </li>
    {% if category_id %}
        <li>
            <span><a href="{% url 'infobox:new_category' pk=category.id %}">{{ category.title }}</a></span>
        </li>
    {% endif %}
        <li>
            <span><a href="{% url 'infobox:edit' pk=infobox.id category_id=category.id %}"><b>Infobox - </b> {{ infobox.title }}</a></span>
        </li>
    <li>
        <span><a>Neues Bittgebet</a></span>
    </li>
{% endblock %}

{% block content %}
    {% include 'supplication/parent_infobox.html' %}
    {% include 'supplication/supplication_form.html' with title="Neues Bittgebet erstellen" button_text="Neues Bittgebet erstellen" %}
{% endblock %}

supplication/templates/supplication/new_variant.html
{% extends 'base/base.html' %}


{% block navigation %}
    <li>
        <span><a href="{% url 'infobox:category' %}">Kategorien</a></span>
    </li>
    {% if category_id %}
        <li>
            <span><a href="{% url 'infobox:new_category' pk=category.id %}">{{ category.title }}</a></span>
        </li>
    {% endif %}
    <li>
        <span><a href="{% url 'infobox:edit' pk=infobox.id category_id=category.id %}"><b>Infobox - </b> {{ infobox.title }}</a></span>
    </li>
    <li>
        <span><a href="{% url 'supplication:edit' pk=infobox.id supplication_id=parent_supplication_data.supplication.id %}"><b>Bittgebet </b> - {{ parent_supplication_data.title }}</a></span>
    </li>
    <li>
        <span><a>Neue Variante</a></span>
    </li>
{% endblock %}

{% block content %}

    {% include 'supplication/parent_supplication.html' %}


    {% include 'supplication/variant_form.html' with title="<b>Neue Variante</b> für Bittgebet erstellen" button_text="Neue Variante erstellen" %}
{% endblock %}

supplication/templates/supplication/parent_infobox.html
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><b>Infobox</b> - {{ infobox.title }}</h2>
          <ul class="nav navbar-right panel_toolbox">
            <li class="dropdown" style="visibility:hidden;">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
              </ul>
            </li>
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="form-horizontal form-label-left">
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Titel
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <p style="padding-top: 8px;">
                          {{ infobox.title }}
                      </p>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Sprache
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <p style="padding-top: 8px;">
                          {{ infobox.language }}
                      </p>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Beschreibung
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <p style="padding-top: 8px;">
                          {{ infobox.description|default:"/" }}
                      </p>
                    </div>
                  </div>
                </div>
            </div>
        </div>
      </div>
    </div>
</div>

supplication/templates/supplication/supplication_form.html
{% extends 'supplication/form.html' %}


{% block supplication_form %}
      <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{ supplication_form.type.id_for_label }}">Art <span class="required">*</span>
          </label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            {{ supplication_form.type }}
            <div style="color:red;">
                {% for error in supplication_form.type.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
          </div>
      </div>
{% endblock %}

supplication/templates/supplication/update_supplication.html
{% extends 'base/base.html' %}


{% block navigation %}
    <li>
        <span><a href="{% url 'infobox:category' %}">Kategorien</a></span>
    </li>
    {% if category_id %}
        <li>
            <span><a href="{% url 'infobox:new_category' pk=category.id %}">{{ category.title }}</a></span>
        </li>
    {% endif %}
    <li>
        <span><a href="{% url 'infobox:edit' pk=infobox.id category_id=category.id %}"><b>Infobox - </b> {{ infobox.title }}</a></span>
    </li>
    <li>
        <span><a>Neues Bittgebet</a></span>
    </li>
{% endblock %}

{% block content %}
    {# include 'supplication/parent_infobox.html' #}
    {% include 'supplication/supplication_form.html' with title="Bittgebet bearbeiten" button_text="Änderungen speichern" %}
    {% include 'supplication/variants.html' with parent_supplication_data=supplication_data %}
    {% url 'supplication:delete' pk=infobox.pk supplication_id=supplication.id as delete_url %}
    {% include 'supplication/delete_panel.html' with delete_url=delete_url%}
{% endblock %}

supplication/templates/supplication/update_variant.html
{% extends 'base/base.html' %}


{% block navigation %}
    <li>
        <span><a href="{% url 'infobox:category' %}">Kategorien</a></span>
    </li>
    {% if category_id %}
        <li>
            <span><a href="{% url 'infobox:new_category' pk=category.id %}">{{ category.title }}</a></span>
        </li>
    {% endif %}
    <li>
        <span><a href="{% url 'infobox:edit' pk=infobox.id category_id=category.id %}"><b>Infobox - </b> {{ infobox.title }}</a></span>
    </li>
    <li>
        <span><a href="{% url 'supplication:edit' pk=infobox.id supplication_id=parent_supplication_data.supplication.id %}"><b>Bittgebet </b> - {{ parent_supplication_data.title }}</a></span>
    </li>
    <li>
        <span><a>Bittgebet Variante bearbeiten</a></span>
    </li>
{% endblock %}

{% block content %}
    {% include 'supplication/parent_supplication.html' %}
    {% include 'supplication/variant_form.html' with title="<b>Bittgebet Variante</b> bearbeiten" button_text="Änderungen speichern" %}
    {% include 'supplication/variants.html' with supplication=supplication.parent %}

    {% url 'supplication:delete_variant' pk=infobox.pk supplication_id=supplication.parent.id supplication_variant_id=supplication.id as delete_url %}
    {% include 'supplication/delete_panel.html' with delete_url=delete_url%}

{% endblock %}

supplication/templates/supplication/variant_form.html
{% extends 'supplication/form.html' %}

supplication/templates/supplication/variants.html
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>{{ supplication_data.title }} <b>Varianten</b></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li class="dropdown" style="visibility: hidden;">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">

              </ul>
            </li>
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                <div class="text-center">
                    <a href="{% url 'supplication:new_variant' pk=infobox.pk supplication_id=supplication.id %}" class="btn btn-info">
                        <span class="glyphicon glyphicon-plus"></span> Neue Variante</a>
                    <br/><br/>
                </div>
                {% if supplication.supplicationvariant_set.all  %}
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Titel</th>
                                <th>Sprache</th>
                                <th class="col-md-2 text-right"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="active">
                                <td>
                                    <p>{{ parent_supplication_data.title }}</p>
                                </td>
                                <td>{{ parent_supplication_data.language }}</td>
                                <td>
                                    <div class="form-group">
                                        <div class="btn-group" style="padding:0;">
                                            <a class="btn" href="{% url 'supplication:edit' pk=infobox.pk supplication_id=supplication.id %}" type="button" style="display:inline-block; border:none; text-decoration: none;padding: 0;margin: 0;background:transparent;">
                                                <span class="glyphicon glyphicon-pencil"></span>
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% for instance in supplication.supplicationvariant_set.all %}
                                {% with supplication_data=instance.supplication_data %}
                                    <tr>
                                        <td>
                                            <p>{{ supplication_data.title }}</p>
                                        </td>
                                        <td>{{ supplication_data.language }}</td>
                                        <td>
                                            <div class="form-group">
                                                <div class="btn-group" style="padding:0;">
                                                    <a class="btn" href="{% url 'supplication:edit_variant' pk=infobox.pk supplication_id=instance.parent_id supplication_variant_id=instance.pk %}" type="button" style="display:inline-block; border:none; text-decoration: none;padding: 0;margin: 0;background:transparent;">
                                                        <span class="glyphicon glyphicon-pencil"></span>
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div class="text-center">
                        <p class="help-block" style="font-size:18px;">Kein Eintrag vorhanden</p>
                    </div>
                {% endif %}
            </div>
        </div>
      </div>
    </div>
</div>